### ISSUE TITLE
can't get netcdf handler to work

### ISSUE THREAD

**Issue by rabernat** [pydap/pydap#165]
I am just trying to run a pydap server in its most simple configuration, to serve netcdf files.

I installed pydap as follows:
```
pip install Pydap[server,handlers.netcdf]
```

Then I ran a pydap server from a directory with netcdf files in it
```
pydap --data .
```

The netcdf (.nc) files are visible in the browser but not active. I can't click them.

The only way I can get them to work is by cloning https://github.com/pydap/pydap.handlers.netcdf and installing that package. But that package hasn't been updated in more than 5 years.

My understanding is that this package (the main pydap package) provides the netcdf handler. I just can't figure out how to properly install the handler.

I would appreciate any advice anyone might have.

**Comment by rabernat** [comment]
Perhaps this is a duplicate of #129?

**Comment by neaptide** [comment]
Hi Ryan:  I had the same problem (approx. 10 months ago) when Pablo answered my plea in the pydap Google Groups forum.

Handlers on Pypi are out of date relative to the new pydap development in github
(pydap) $ pip install pydap.handlers.netcdf

# get the lastest code -- to see dds, das, html repsonse on webrowser, without this it doesn't work
# posted answer on Google Groups listserve for pydap -- https://groups.google.com/forum/#!topic/pydap/IAXuHXXycNM
(pydap) $ pip install git+https://github.com/pydap/pydap.handlers.netcdf.git
# to install server
(pydap) $ pip install pydap[server]
(pydap) $ pip install pydap[handlers.netcdf] # only installs dependencies but not code for handler
(pydap) $ pip install pydap[functions]          # to install coards (1.0.5) and gsw (3.0.6) since it crashes without these

**Comment by rabernat** [comment]
I am still having this problem. What is the best way to install the netcdf handlers?

cc @TanBowen

**Comment by Juanlu001** [comment]
Also, `pip install pydap.handlers.netcdf` is Python 2 only:

```
$ pip install pydap.handlers.netcdf
Collecting pydap.handlers.netcdf
  Downloading https://files.pythonhosted.org/packages/33/a3/994079b67cadb9db6972a64d6790f37113dcff1778be4f3ba5225aad5f11/pydap.handlers.netcdf-0.6.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7145vvpe/pydap.handlers.netcdf/setup.py", line 6, in <module>
        import paver.tasks
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 906, in _find_spec
      File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
      File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
      File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
      File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
      File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
      File "paver-minilib.zip/paver/tasks.py", line 69
        print output
                   ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(output)?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7145vvpe/pydap.handlers.netcdf/
```
