### ISSUE TITLE
pydap fails with Python 3.10

### ISSUE THREAD

**Issue by MHee** [pydap/pydap#264]
The import

> from collections import OrderedDict, Mapping

in model.py fails with Python 3.10

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> Input In [700], in <cell line: 1>()
> ----> 1 from collections import OrderedDict, Mapping
> 
> ImportError: cannot import name 'Mapping' from 'collections' (C:\Data\miniconda3\envs\tides\lib\collections\__init__.py)

This seems to be a known problem with an easy fix:
https://stackoverflow.com/a/71438295

The change of the line below seems to fix the problem:

> from collections import OrderedDict
> 
> try:
>     from collections.abc import Mapping
> except ImportError:
>     from collections import Mapping
>

**Comment by MHee** [comment]
Never mind, pip installed an older version.

> conda install -c conda-forge pydap

installed pydap-3.3.0 and fixed the problem...

**Comment by theendlessriver13** [comment]
There was no release to PyPi since 2017, so the latest version there is `3.2.2` https://pypi.org/project/Pydap/#history.

Unfortunately this breaks `xarray[io]` for me on python3.10 
https://github.com/pydata/xarray/blob/e5fcd7935df16e3a5c168f4b64ddcb4d619570da/setup.cfg#L83

Would it be possible to make a release of `3.3.0` to PyPi as well?
