### ISSUE TITLE
Extend PyDAP to support EDL tokens

### ISSUE THREAD

**Issue by jgallagher59701** [pydap/pydap#298]
[Chris Lindsley](https://bugs.earthdata.nasa.gov/secure/ViewProfile.jspa?name=lindsley) requested an update to PyDAP to allow authentication using EDL bearer tokens. Using https://github.com/michele-personal/earthdata_hyraxOPeNDAP_access/blob/main/DaymetV4_access_subsetting_HyraxError.ipynb as an example, it looks like PyDAP currently supports session creation with EDL username and password input, so this potentially would allow an additional input in the form of EDL bearer token (https://wiki.earthdata.nasa.gov/display/EL/API+Documentation).

NB: EDL Tokens are really an instance of a more general feature to support token-based authentication.

**Comment by Mikejmnez** [comment]
@ndp-opendap share [THIS](https://opendap.github.io/documentation/tutorials/ClientAuthenticationWithEDLTokens.html) very useful and relevant resource which effectively solves this issue about using EDL bearer tokens to access Earthdata datasets. That resource effectively demonstrate that <ins>PyDAP already supports EDL tokens</ins>. That alone should close this issue.

However, I ran into an issue when trying to access test data following that tutorial. That issue is likely related to a deprecated package/library that pydap depends on.  

As a result, I <ins>will close</ins> this issue as completed since pydap support EDL tokens, but I will open a separate issue detailing the current behavior of pydap when using token. Feel free to re-open.
