### ISSUE TITLE
PyDap server is missing log/branding graphics (they moved)

### ISSUE THREAD

**Issue by ndp-opendap** [pydap/pydap#363]
When the pydap"[server']" is run the logo image (i.e. the meatball) is missing from the navigation (catalog) pages.
For this example, launch pydap:
```
pydap --data /usr/share/test-data  --port 8080 
```
Then on this page: `http://127.0.0.1:8080/`
There is a broken link at the top that points to: 
```
https://www.opendap.org/sites/default/files/OPeNDAP-meatball.png
```
Broken because there is no longer such a file at that location (there used to be but.. maybe not for a long while)

Here is a link to the "meatball" from our GitHub organization's avatar image: https://avatars.githubusercontent.com/u/8326701?s=200&v=4
But I don't know where we officially keep all that identity /branding content.

Miguel Jimenez-Urias
 Yeah - I know where the png file is. I can add it to the repo and point the template to use that instead (edited) 
 I have been wanting to work on that html part of the pydap's server for some time

**Comment by Mikejmnez** [comment]
@ndp-opendap would it make sense to have define that URL within pydap's server's html files instead of a local file in the repo? I guess the question is how `static` is [this](https://avatars.githubusercontent.com/u/8326701?s=200&v=4) url?

Here is the relevant snippet
https://github.com/pydap/pydap/blob/012fcb42b3305373729fb815ab51e87a42d042a2/src/pydap/wsgi/templates/base.html#L49-L51
