### ISSUE TITLE
Following the README instructions led to a failure on import

### ISSUE THREAD

**Issue by tennlee** [pydap/pydap#371]
I installed pydap and ran the following:

```
import pydap
from pydap.client import open_url
```

This led to the following error:

```
lib/python3.12/site-packages/pydap/responses/lib.py#line=20), in load_responses()
     19 def load_responses():
     20     """Load all available responses from the system, returning a dictionary."""
---> 21     eps = entry_points(group="pydap.response")
     22     Rs = [r for r in eps if r.module[:5] == "pydap"]
     23     nRs = [r for r in eps if r.module[:5] != "pydap"]

TypeError: entry_points() got an unexpected keyword argument 'group'
```

I'm happy to help debug this but thought I would report it.

**Comment by Mikejmnez** [comment]
@tennlee could you share the environment where you ran into these issues? I would like to replicate the error. I think I remember seeing this error back when we set the [implicit discovery of entry_points](https://github.com/pydap/pydap/pull/346). I no longer remember what the issue with that, but it got around it.

Also -  since `pydap 3.5` released last Aug and available via pip and conda installs,  `pydap` is only compatible with numpy>=2.0. And so the fact that `pydap` is even running in your system with numpy 1.26 probably means something went wrong during the initial installation...

Thanks again!

**Comment by tennlee** [comment]
I tried this again and it didn't reproduce. That was a bit of a surprise because I hadn't done anything out of the ordinary. I will try again in the next couple of days, but perhaps this one isn't a big problem. It could be some quirk of the dependency resolution which just doesn't apply any more.

**Comment by Mikejmnez** [comment]
Tat is good news! Thanks for checking back and do let us know if this is a problem later.

**Comment by Mikejmnez** [comment]
Closing this. Feel free to open if this remains an issue. Thanks again!
